apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: wordpress3
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
